/* media.js — GENERATED by scripts/fetch_audio.py and scripts/make_silhouette.py.
   Maps bird id -> local media so the game never reveals the answer via a
   query-string. Do not edit by hand; re-run the pipelines instead. */
const BirdMedia = {
  "american-robin": {
    "audio": "audio/american-robin.m4a",
    "audioAttribution": "iNaturalist (c) meswift, CC-BY-NC — observation 153438595",
    "imageArtist": "Rhododendrites",
    "imageLicense": "CC BY-SA 4.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:American_robin_(71307).jpg",
    "silhouette": "svg/silhouettes/species/american-robin.png"
  },
  "shoebill": {
    "audio": false,
    "audioAttribution": false,
    "imageArtist": "Bob Owen",
    "imageLicense": "CC BY 2.0",
    "imageLicenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "imageSource": "https://commons.wikimedia.org/wiki/File:Balaeniceps_rex_-Ueno_Zoo,_Tokyo,_Japan-8a.jpg",
    "silhouette": "svg/silhouettes/species/shoebill.png"
  }
};
