/* ui.js — All DOM rendering and updates (hub-and-spoke) */

const UI = (() => {
  // The 5 clue spokes, in unlock order. `pos` maps to a grid area (s1..s5) laid
  // out as a point-up pentagon around the hub (see .hub-spoke in styles.css).
  // Each clue has a ghost icon shown while locked, hinting at the reward to come
  // (a waveform for song, a leaf for habitat, etc.) instead of a generic "?".
  const ICON = {
    song: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><path d="M4 9.5v5M8 6v12M12 9v6M16 4v16M20 9.5v5"/></svg>',
    habitat: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 19C5 11 11 5 19 5c0 8-6 14-14 14z"/><path d="M5.5 18.5C8 14 11.5 11 15 9.5"/></svg>',
    behaviour: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12z"/><circle cx="12" cy="12" r="2.6"/></svg>',
    silhouette: '<svg viewBox="0 0 24 24" fill="currentColor"><path d="M22 6.3c-.8.4-1.6.6-2.5.7a4.3 4.3 0 0 0 1.9-2.4c-.8.5-1.8.9-2.8 1.1a4.3 4.3 0 0 0-7.4 3.9C7.4 9.4 4.1 7.6 1.9 4.8a4.3 4.3 0 0 0 1.3 5.8c-.7 0-1.4-.2-2-.5a4.3 4.3 0 0 0 3.5 4.3c-.6.2-1.3.2-2 .1a4.3 4.3 0 0 0 4 3 8.7 8.7 0 0 1-6.4 1.8 12.2 12.2 0 0 0 18.8-10.3v-.6c.8-.6 1.5-1.3 2-2.2z"/></svg>',
    photo: '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linejoin="round"><rect x="3" y="5" width="18" height="14"/><circle cx="8.5" cy="10" r="1.6"/><path d="M21 16l-5-5-8 7"/></svg>',
  };
  const CLUES = [
    { n: 1, key: 'song',       pos: 's1', label: 'Bird Song' },
    { n: 2, key: 'habitat',    pos: 's2', label: 'Habitat & Range' },
    { n: 3, key: 'behaviour',  pos: 's3', label: 'Behaviour & Diet' },
    { n: 4, key: 'silhouette', pos: 's4', label: 'Silhouette' },
    { n: 5, key: 'photo',      pos: 's5', label: 'Full Photo' },
  ];

  const el = id => document.getElementById(id);
  let _bird = null; // current bird, for spoke content rendering

  // Local media (audio + species silhouette) keyed by bird id, generated by the
  // Python pipelines into js/media.js. Falls back gracefully if absent.
  const media = id => (typeof BirdMedia !== 'undefined' && BirdMedia[id]) || {};
  // Resolve a repo-relative media path against ASSET_BASE (a CDN when hosted on Pages,
  // empty locally). Absolute URLs pass through untouched.
  const assetUrl = p =>
    (p && window.ASSET_BASE && !/^https?:\/\//.test(p))
      ? window.ASSET_BASE.replace(/\/$/, '') + '/' + p.replace(/^\//, '')
      : p;
  // Bird photo: prefer the self-hosted local copy (served via CDN when hosted); fall back
  // to the original Wikimedia Commons URL (which is also the credit source link).
  const photoUrl = bird => assetUrl(media(bird.id).photo) || bird.imageUrl;

  // ── Screens ─────────────────────────────────────────────────────────────
  function showScreen(name) {
    const loading = el('screen-loading');
    if (loading) loading.hidden = true;
    ['screen-archive', 'screen-game'].forEach(id => {
      el(id).hidden = (id !== `screen-${name}`);
    });
  }

  // ── Context bar ───────────────────────────────────────────────────────────
  function setContext(mode, archiveLabel) {
    const ctx = el('game-context');
    if (mode === 'archive') {
      ctx.innerHTML =
        `<span class="ctx-label">Archive</span>` +
        `<span class="ctx-date">${escHtml(archiveLabel || '')}</span>` +
        `<button class="link-btn" id="btn-back-archive">← All archive birds</button>`;
    } else {
      const today = new Date();
      const dateStr = today.toLocaleDateString('en-US', { weekday: 'long', month: 'long', day: 'numeric' });
      ctx.innerHTML = `<span class="ctx-label">Daily Bird</span><span class="ctx-date">${dateStr}</span>`;
    }
  }

  // ── Guess counter ──────────────────────────────────────────────────────────
  function setGuessBadge(guessNum) {
    el('guess-badge').textContent = `Guess ${guessNum} of 5`;
  }

  // ── Spokes ─────────────────────────────────────────────────────────────────
  function renderSpokes(bird) {
    _bird = bird;
    const container = el('hub-spoke');
    // Remove previous spokes (keep the hub)
    container.querySelectorAll('.spoke').forEach(s => s.remove());

    CLUES.forEach(clue => {
      const spoke = document.createElement('div');
      spoke.className = `spoke spoke--${clue.pos} spoke--${clue.key}`;
      spoke.setAttribute('data-clue', String(clue.n));
      spoke.setAttribute('data-locked', 'true');
      spoke.innerHTML =
        `<div class="spoke-head">` +
          `<span class="spoke-num">${clue.n}</span>` +
          `<span class="spoke-label">${clue.label}</span>` +
        `</div>` +
        `<div class="spoke-body">` +
          `<div class="spoke-locked" aria-label="Locked — make a wrong guess to unlock">${ICON[clue.key]}</div>` +
          `<div class="spoke-content"></div>` +
        `</div>`;
      // Insert spokes before the hub so source order is clue 1..5 then hub
      container.insertBefore(spoke, el('game-hub'));
      // Tilt only on the two non-interactive image spokes
      if (clue.key === 'silhouette' || clue.key === 'photo') attachTilt(spoke);
    });
  }

  // Reveal all spokes up to `count` (1–5); lock the rest.
  function setUnlockedClues(count) {
    CLUES.forEach(clue => {
      const spoke = document.querySelector(`.spoke[data-clue="${clue.n}"]`);
      if (!spoke) return;
      const unlocked = clue.n <= count;
      const wasLocked = spoke.getAttribute('data-locked') === 'true';
      spoke.setAttribute('data-locked', unlocked ? 'false' : 'true');
      if (unlocked && wasLocked) {
        fillSpokeContent(clue, spoke.querySelector('.spoke-content'));
      } else if (!unlocked) {
        spoke.querySelector('.spoke-content').innerHTML = '';
      }
    });
  }

  function fillSpokeContent(clue, target) {
    const bird = _bird;
    if (!bird || !target) return;
    switch (clue.key) {
      case 'song':
        target.innerHTML = '';
        target.appendChild(buildAudio(bird));
        break;
      case 'habitat':
        target.innerHTML = `<p class="spoke-text">${escHtml(bird.hints?.region || '')}</p>`;
        break;
      case 'behaviour':
        target.innerHTML = `<p class="spoke-text">${escHtml(bird.hints?.behavior || '')}</p>`;
        break;
      case 'silhouette': {
        // Prefer the per-species silhouette from the pipeline; fall back to the
        // generic body-type SVG. Both render as <img> (reliable over file://).
        const src = media(bird.id).silhouette
          || `svg/silhouettes/${bird.silhouetteType || 'passerine'}.svg`;
        target.innerHTML =
          `<img class="spoke-silhouette-img" src="${escHtml(src)}" alt="Bird silhouette" draggable="false">`;
        break;
      }
      case 'photo': {
        const img = document.createElement('img');
        img.className = 'spoke-photo';
        img.alt = 'Mystery bird';
        img.draggable = false;
        img.onerror = () => {
          if (img.src !== bird.imageUrl && bird.imageUrl) { img.src = bird.imageUrl; }
          else { target.classList.add('spoke-img-error'); }
        };
        img.src = photoUrl(bird);
        target.innerHTML = '';
        target.appendChild(img);
        break;
      }
    }
  }

  function buildAudio(bird) {
    const wrap = document.createElement('div');
    wrap.className = 'spoke-audio-wrap';
    // Use ONLY the locally-hosted clip (no query string that could reveal the
    // species). Birds without an open recording show a neutral empty state.
    const src = assetUrl(media(bird.id).audio);
    if (src) {
      wrap.innerHTML =
        `<audio class="spoke-audio-player" controls preload="none" src="${escHtml(src)}">` +
        `Your browser does not support audio playback.</audio>`;
    } else {
      wrap.innerHTML = `<p class="spoke-text spoke-text--muted">No recording available for this bird yet.</p>`;
    }
    return wrap;
  }

  // ── Archive picker ──────────────────────────────────────────────────────────
  function renderArchivePicker(entries, onPick) {
    const list = el('archive-list');
    list.innerHTML = '';
    entries.forEach(entry => {
      const item = document.createElement('button');
      item.className = 'archive-item';
      item.setAttribute('role', 'listitem');
      item.setAttribute('data-offset', String(entry.offset));
      // No bird name — spoiler prevention. Date label only.
      item.innerHTML =
        `<span class="archive-item-label">${escHtml(entry.label)}</span>` +
        `<span class="archive-item-date">${escHtml(entry.dateStr)}</span>` +
        `<span class="archive-item-go">Play →</span>`;
      item.addEventListener('click', () => onPick(entry.offset));
      list.appendChild(item);
    });
  }

  // ── Autocomplete ──────────────────────────────────────────────────────────
  let _onSuggestionSelect = null;
  let _activeSuggestionIdx = -1;
  let _suggestions = [];

  function showGuessSuggestions(birds, onSelect) {
    _onSuggestionSelect = onSelect;
    _suggestions = birds;
    _activeSuggestionIdx = -1;
    const list = el('guess-suggestions');
    list.innerHTML = '';
    if (!birds.length) { list.hidden = true; return; }
    birds.forEach((bird, i) => {
      const item = document.createElement('div');
      item.className = 'suggestion-item';
      item.setAttribute('role', 'option');
      item.setAttribute('data-idx', i);
      item.textContent = bird.commonName;
      item.addEventListener('mousedown', e => { e.preventDefault(); selectSuggestion(i); });
      list.appendChild(item);
    });
    list.hidden = false;
  }

  function hideGuessSuggestions() {
    el('guess-suggestions').hidden = true;
    _suggestions = [];
    _activeSuggestionIdx = -1;
  }

  function navigateSuggestions(direction) {
    const items = el('guess-suggestions').querySelectorAll('.suggestion-item');
    if (!items.length) return;
    items[_activeSuggestionIdx]?.classList.remove('suggestion-item--active');
    _activeSuggestionIdx = Math.max(0, Math.min(items.length - 1, _activeSuggestionIdx + direction));
    const active = items[_activeSuggestionIdx];
    active.classList.add('suggestion-item--active');
    el('guess-input').value = _suggestions[_activeSuggestionIdx].commonName;
  }

  function selectSuggestion(idx) {
    const bird = _suggestions[idx];
    if (!bird) return;
    el('guess-input').value = bird.commonName;
    hideGuessSuggestions();
    _onSuggestionSelect?.(bird.commonName);
  }

  function getActiveSuggestionIdx() { return _activeSuggestionIdx; }

  // ── Guess history ─────────────────────────────────────────────────────────
  function clearGuessHistory() { el('guess-history').innerHTML = ''; }

  function addGuessToHistory(text, correct, hint) {
    const row = document.createElement('div');
    row.className = `guess-row-item guess-row-item--${correct ? 'correct' : 'wrong'}`;
    let html =
      `<span class="guess-row-icon">${correct ? '✓' : '✗'}</span>` +
      `<span class="guess-row-text">${escHtml(text)}</span>`;
    if (!correct && hint) {
      let msg;
      if (hint.group) {
        const article = /^[aeiou]/.test(hint.group) ? 'an' : 'a';
        msg = `Close — it's ${article} ${escHtml(hint.group)} too!`;
      } else {
        msg = `Close — a close relative!`;
      }
      html += `<span class="guess-row-hint">${msg}</span>`;
      row.classList.add('guess-row-item--close');
    }
    row.innerHTML = html;
    el('guess-history').appendChild(row);
  }

  // ── Guess input state ─────────────────────────────────────────────────────
  function setGuessInputEnabled(enabled) {
    el('guess-input').disabled = !enabled;
    el('btn-guess').disabled = !enabled;
  }

  function clearGuessInput() { el('guess-input').value = ''; }

  function shakeGuessInput() {
    const input = el('guess-input');
    input.classList.remove('shake');
    void input.offsetWidth;
    input.classList.add('shake');
  }

  // Brief red border flash on the input for a wrong (but valid) guess.
  function flashWrongGuess() {
    const input = el('guess-input');
    input.classList.remove('flash-wrong');
    void input.offsetWidth;
    input.classList.add('flash-wrong');
  }

  // Brief accent pulse confirming an autocomplete pick (neutral acknowledgement).
  function flashSelect() {
    const input = el('guess-input');
    input.classList.remove('flash-select');
    void input.offsetWidth;
    input.classList.add('flash-select');
  }

  function setGuessError(msg) {
    let err = el('guess-error-msg');
    if (!err) {
      err = document.createElement('p');
      err.id = 'guess-error-msg';
      err.className = 'guess-error';
      el('guess-area').insertBefore(err, el('guess-history'));
    }
    err.textContent = msg;
    clearTimeout(err._timer);
    err._timer = setTimeout(() => { err.textContent = ''; }, 2000);
  }

  // ── Bird card overlay ─────────────────────────────────────────────────────
  function showBirdCard({ bird, won, guessCount, mode, shareText, shareLine }) {
    const card = el('overlay-card');

    const resultEl = el('card-result');
    if (won) {
      resultEl.className = 'card-result card-result--correct';
      resultEl.textContent = guessCount === 1 ? 'Solved on the song alone!' : `Solved on clue ${guessCount} of 5`;
    } else {
      resultEl.className = 'card-result card-result--wrong';
      resultEl.textContent = 'Out of guesses — nice try!';
    }

    const cardPhoto = el('card-photo');
    cardPhoto.onerror = () => {
      if (cardPhoto.src !== bird.imageUrl && bird.imageUrl) cardPhoto.src = bird.imageUrl;
    };
    cardPhoto.src = photoUrl(bird);
    cardPhoto.alt = bird.commonName;
    el('card-name').textContent = bird.commonName;
    el('card-name').classList.toggle('card-name--win', !!won); // one-time light-catch sheen on a win
    el('card-sci').textContent = bird.scientificName;

    // Facts
    const factsList = el('card-facts');
    factsList.innerHTML = '';
    [
      { key: 'size', label: 'Size' },
      { key: 'habitat', label: 'Habitat' },
      { key: 'diet', label: 'Diet' },
      { key: 'migration', label: 'Migration' },
    ].forEach(({ key, label }) => {
      if (bird.facts?.[key]) {
        const li = document.createElement('li');
        li.innerHTML = `<strong>${label}:</strong> ${escHtml(bird.facts[key])}`;
        factsList.appendChild(li);
      }
    });
    if (bird.funFact) {
      const li = document.createElement('li');
      li.className = 'card-fun-fact';
      li.innerHTML = `<strong>Fun fact:</strong> ${escHtml(bird.funFact)}`;
      factsList.appendChild(li);
    }

    // Audio — local clip if we have one, else the Xeno-canto link (fine post-reveal)
    const audioWrap = el('card-audio');
    const audioPlayer = el('card-audio-player');
    const xenoWrap = el('card-xeno');
    const localAudio = assetUrl(media(bird.id).audio);
    if (localAudio) {
      audioPlayer.src = localAudio;
      audioWrap.hidden = false;
      xenoWrap.hidden = true;
    } else {
      audioWrap.hidden = true;
      const query = encodeURIComponent(bird.xenoCantoQuery || bird.commonName);
      el('card-xeno-link').href = `https://xeno-canto.org/explore?query=${query}`;
      xenoWrap.hidden = false;
    }

    // External links
    const linksEl = el('card-ext-links');
    linksEl.innerHTML = '';
    if (bird.ebirdUrl) {
      linksEl.innerHTML += `<a class="card-ext-link" href="${bird.ebirdUrl}" target="_blank" rel="noopener">View on eBird ↗</a>`;
    }
    if (bird.audubonUrl) {
      linksEl.innerHTML += `<a class="card-ext-link" href="${bird.audubonUrl}" target="_blank" rel="noopener">Audubon Guide ↗</a>`;
    }

    // Point-of-use photo attribution (CC-BY / CC-BY-SA compliance)
    const creditEl = el('card-credit');
    const cm = media(bird.id);
    if (cm.imageArtist) {
      const lic = cm.imageLicenseUrl
        ? `<a href="${escHtml(cm.imageLicenseUrl)}" target="_blank" rel="noopener">${escHtml(cm.imageLicense || 'license')}</a>`
        : escHtml(cm.imageLicense || '');
      const src = cm.imageSource
        ? `<a href="${escHtml(cm.imageSource)}" target="_blank" rel="noopener">Wikimedia Commons</a>`
        : 'Wikimedia Commons';
      creditEl.innerHTML = `Photo: ${escHtml(cm.imageArtist)} / ${src} (${lic})`;
      creditEl.hidden = false;
    } else {
      creditEl.hidden = true;
    }

    // Share (daily only) vs. Back-to-archive (archive only)
    const shareBlock = el('card-share');
    const btnShare = el('btn-card-share');
    const btnNext = el('btn-card-next');
    if (mode === 'daily') {
      shareBlock.hidden = false;
      el('share-preview').innerHTML = buildShareSegments(won, won ? guessCount : 0);
      el('share-line').textContent = shareLine || '';
      btnShare.hidden = false;
      btnShare.dataset.text = shareText || '';
      btnShare.onclick = () => shareResult(shareText, btnShare);
      btnNext.hidden = true;
      startCountdown();
    } else {
      shareBlock.hidden = true;
      btnShare.hidden = true;
      btnNext.hidden = false;
      stopCountdown();
    }

    card.hidden = false;
    document.body.classList.add('overlay-open');
  }

  // 5-segment row: filled up to the solve clue (win) or all-X (fail). Filled
  // segments pop in in sequence (echoing the spoke-unlock cadence).
  function buildShareSegments(won, solveClue) {
    let html = '';
    for (let i = 1; i <= 5; i++) {
      const delay = (0.55 + (i - 1) * 0.08).toFixed(2);
      if (won && i <= solveClue) html += `<span class="seg seg--filled" style="animation-delay:${delay}s"></span>`;
      else if (!won) html += '<span class="seg seg--fail">✕</span>';
      else html += '<span class="seg"></span>';
    }
    return html;
  }

  // Live countdown to the next daily bird (local midnight).
  let _cdTimer = null;
  function startCountdown() {
    const node = el('card-countdown'); if (!node) return;
    const tick = () => {
      const now = new Date();
      const next = new Date(now.getFullYear(), now.getMonth(), now.getDate() + 1, 0, 0, 0, 0);
      let s = Math.max(0, Math.floor((next - now) / 1000));
      const h = String(Math.floor(s / 3600)).padStart(2, '0');
      const m = String(Math.floor((s % 3600) / 60)).padStart(2, '0');
      s = String(s % 60).padStart(2, '0');
      node.textContent = `Next bird in ${h}:${m}:${s}`;
    };
    tick();
    clearInterval(_cdTimer);
    _cdTimer = setInterval(tick, 1000);
  }
  function stopCountdown() { clearInterval(_cdTimer); _cdTimer = null; }

  function hideBirdCard() {
    stopCountdown();
    el('overlay-card').hidden = true;
    document.body.classList.remove('overlay-open');
    const player = el('card-audio-player');
    if (player && !player.paused) player.pause();
  }

  // ── Credits modal ─────────────────────────────────────────────────────────
  function showCredits() {
    const list = el('credits-list');
    list.innerHTML = '';
    (typeof Birds !== 'undefined' ? Birds.getAllBirds() : []).forEach(b => {
      const m = media(b.id);
      if (!m.imageArtist && !m.audioAttribution) return;
      const row = document.createElement('div');
      row.className = 'credit-row';
      let h = `<span class="credit-name">${escHtml(b.commonName)}</span>`;
      if (m.imageArtist) {
        const lic = m.imageLicenseUrl
          ? `<a href="${escHtml(m.imageLicenseUrl)}" target="_blank" rel="noopener">${escHtml(m.imageLicense || 'license')}</a>`
          : escHtml(m.imageLicense || '');
        const photo = m.imageSource
          ? `<a href="${escHtml(m.imageSource)}" target="_blank" rel="noopener">photo</a>`
          : 'photo';
        h += `<span class="credit-meta">${photo}: ${escHtml(m.imageArtist)} (${lic})</span>`;
      }
      if (m.audioAttribution) {
        h += `<span class="credit-meta">audio: ${escHtml(m.audioAttribution)}</span>`;
      }
      row.innerHTML = h;
      list.appendChild(row);
    });
    el('overlay-credits').hidden = false;
    document.body.classList.add('overlay-open');
  }

  function hideCredits() {
    el('overlay-credits').hidden = true;
    document.body.classList.remove('overlay-open');
  }

  // ── Help modal ────────────────────────────────────────────────────────────
  function showHelp() {
    el('overlay-help').hidden = false;
    document.body.classList.add('overlay-open');
  }
  function hideHelp() {
    el('overlay-help').hidden = true;
    document.body.classList.remove('overlay-open');
  }

  // ── Region selector (clickable world map) ──────────────────────────────────
  let _regionMeta = {}; // key -> { label, emoji }
  function showRegionMap() {
    el('overlay-region').hidden = false;
    document.body.classList.add('overlay-open');
  }
  function hideRegionMap() {
    el('overlay-region').hidden = true;
    document.body.classList.remove('overlay-open');
  }
  function buildRegionSelector(regions, current, onChange) {
    _regionMeta = {};
    regions.forEach(r => { _regionMeta[r.key] = { label: r.label, emoji: r.emoji || '' }; });

    const pick = (key) => { onChange(key); hideRegionMap(); };

    el('btn-region').addEventListener('click', showRegionMap);
    document.querySelectorAll('#overlay-region .land').forEach(path => {
      path.addEventListener('click', () => pick(path.dataset.region));
      path.addEventListener('keydown', e => {
        if (e.key === 'Enter' || e.key === ' ') { e.preventDefault(); pick(path.dataset.region); }
      });
    });
    el('btn-region-global').addEventListener('click', () => pick('global'));
    el('btn-close-region').addEventListener('click', hideRegionMap);
    el('overlay-region').addEventListener('click', e => { if (e.target === e.currentTarget) hideRegionMap(); });

    setRegionValue(current);
    el('region-bar').hidden = false;
  }
  function setRegionValue(key) {
    const meta = _regionMeta[key] || { label: 'Global', emoji: '' };
    const lbl = el('region-pick-label');
    if (lbl) lbl.textContent = meta.label;
    document.querySelectorAll('#overlay-region .land').forEach(p =>
      p.classList.toggle('land--sel', p.dataset.region === key));
    const gb = el('btn-region-global');
    if (gb) gb.classList.toggle('region-global-btn--sel', key === 'global');
  }

  // ── Stats modal ───────────────────────────────────────────────────────────
  const prefersReduced = () => matchMedia('(prefers-reduced-motion: reduce)').matches;
  let _lastMilestone = -1;
  function countUp(id, to) {
    const node = el(id); if (!node) return;
    if (prefersReduced()) { node.textContent = to; return; }
    const dur = 600, start = performance.now();
    function tick(now) {
      const t = Math.min((now - start) / dur, 1);
      node.textContent = Math.round(to * (1 - Math.pow(1 - t, 3))); // ease-out cubic, no overshoot
      if (t < 1) requestAnimationFrame(tick);
    }
    requestAnimationFrame(tick);
  }
  function showStats(stats, regionLabel) {
    const rEl = el('stats-region');
    if (rEl) rEl.textContent = regionLabel ? `${regionLabel} · daily` : '';
    const winPct = stats.played ? Math.round((stats.wins / stats.played) * 100) : 0;
    countUp('stat-played', stats.played);
    countUp('stat-win-pct', winPct);
    countUp('stat-streak', stats.streak);
    countUp('stat-max-streak', stats.maxStreak);

    // One-time flourish when the streak lands on a milestone.
    const cell = el('stat-streak') && el('stat-streak').closest('.stat-cell');
    if (cell) {
      cell.classList.remove('stat-cell--milestone');
      if ([3, 7, 14, 30, 50, 100].includes(stats.streak) && stats.streak !== _lastMilestone && !prefersReduced()) {
        void cell.offsetWidth;
        cell.classList.add('stat-cell--milestone');
        _lastMilestone = stats.streak;
      }
    }

    const distEl = el('guess-dist');
    distEl.innerHTML = '';
    const max = Math.max(...stats.dist, 1);
    const labels = ['1', '2', '3', '4', '5', 'X'];
    const pcts = [];
    stats.dist.forEach((count, i) => {
      const pct = Math.max(Math.round((count / max) * 100), count > 0 ? 4 : 0);
      pcts.push(pct);
      const row = document.createElement('div');
      row.className = 'dist-row';
      const w = prefersReduced() ? pct : 0;
      row.innerHTML =
        `<span class="dist-num">${labels[i]}</span>` +
        `<div class="dist-bar-wrap"><div class="dist-bar${i === 5 ? ' dist-bar--fail' : ''}" style="width:${w}%">${count || ''}</div></div>`;
      distEl.appendChild(row);
    });
    if (!prefersReduced()) {
      requestAnimationFrame(() => distEl.querySelectorAll('.dist-bar').forEach((b, i) => { b.style.width = pcts[i] + '%'; }));
    }

    el('overlay-stats').hidden = false;
    document.body.classList.add('overlay-open');
  }
  function hideStats() {
    el('overlay-stats').hidden = true;
    document.body.classList.remove('overlay-open');
  }

  // ── Share ─────────────────────────────────────────────────────────────────
  async function shareResult(text, btn) {
    if (navigator.share) {
      try { await navigator.share({ title: 'Birdle', text }); return; }
      catch (_) { /* fallthrough to clipboard */ }
    }
    try { await navigator.clipboard.writeText(text); } catch (_) { /* ignore */ }
    flashCopied(btn);
  }
  // In-place confirmation morph (replaces the old blocking alert).
  function flashCopied(btn) {
    if (!btn || btn._copying) return;
    btn._copying = true;
    const orig = btn.textContent;
    btn.textContent = 'Copied ✓';
    btn.classList.add('is-copied');
    setTimeout(() => {
      btn.textContent = orig; btn.classList.remove('is-copied'); btn._copying = false;
    }, 1700);
  }

  // ── Utility ───────────────────────────────────────────────────────────────
  function escHtml(str) {
    return String(str)
      .replace(/&/g, '&amp;')
      .replace(/</g, '&lt;')
      .replace(/>/g, '&gt;')
      .replace(/"/g, '&quot;');
  }

  // ── Cursor interaction ──────────────────────────────────────────────────────
  // Tilt is applied ONLY to image spokes (silhouette/photo) — they have no
  // interactive children, so shifting their bounding box can't break clicks.
  // The hub (which holds the input + autocomplete) is never transformed; it only
  // gets a spotlight gradient via --mx/--my.
  function attachTilt(node) {
    node.addEventListener('mousemove', e => {
      const r = node.getBoundingClientRect();
      const dx = (e.clientX - r.left - r.width / 2) / (r.width / 2);
      const dy = (e.clientY - r.top - r.height / 2) / (r.height / 2);
      node.style.transition = 'transform 0.08s ease-out';
      node.style.transform = `perspective(700px) rotateX(${(-dy * 5).toFixed(2)}deg) rotateY(${(dx * 7).toFixed(2)}deg)`;
    });
    node.addEventListener('mouseleave', () => {
      node.style.transition = 'transform 0.55s cubic-bezier(0.22,1,0.36,1)';
      node.style.transform = '';
    });
  }

  (function initHubSpotlight() {
    const hub = el('game-hub');
    if (!hub) return;
    hub.addEventListener('mousemove', e => {
      const r = hub.getBoundingClientRect();
      hub.style.setProperty('--mx', `${(e.clientX - r.left).toFixed(0)}px`);
      hub.style.setProperty('--my', `${(e.clientY - r.top).toFixed(0)}px`);
    });
    hub.addEventListener('mouseleave', () => {
      hub.style.setProperty('--mx', '50%');
      hub.style.setProperty('--my', '50%');
    });
  })();

  return {
    showScreen,
    setContext,
    setGuessBadge,
    renderSpokes,
    setUnlockedClues,
    renderArchivePicker,
    showGuessSuggestions,
    hideGuessSuggestions,
    navigateSuggestions,
    getActiveSuggestionIdx,
    clearGuessHistory,
    addGuessToHistory,
    setGuessInputEnabled,
    clearGuessInput,
    shakeGuessInput,
    flashWrongGuess,
    flashSelect,
    setGuessError,
    showBirdCard,
    hideBirdCard,
    showHelp,
    hideHelp,
    showStats,
    hideStats,
    buildRegionSelector,
    setRegionValue,
    showCredits,
    hideCredits,
  };
})();
