# -*- coding: utf-8 -*-
"""
birdle_lib — shared helpers for the Birdle media pipelines.

Both pipelines (fetch_audio.py, make_silhouette.py) read the canonical bird list
straight out of js/birds.js and read/write a generated js/media.js map:

    const BirdMedia = { "<bird-id>": { "audio": "...", "silhouette": "...", ... }, ... };

js/media.js is loaded as a plain <script> (no fetch) so the game keeps working when
index.html is opened directly via file://. This module is stdlib-only.
"""
import json, os, re

REPO_ROOT    = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BIRDS_JS     = os.path.join(REPO_ROOT, "js", "birds.js")
INGESTED_JS  = os.path.join(REPO_ROOT, "js", "birds_ingested.js")  # generated mass pool
MEDIA_JS     = os.path.join(REPO_ROOT, "js", "media.js")

# Matches a bird's id/commonName/scientificName header line. Backreferences on the
# quote char let commonName contain an apostrophe (e.g. "Anna's Hummingbird").
_HDR = re.compile(
    r"id:\s*(['\"])(?P<id>[a-z0-9\-]+)\1\s*,\s*"
    r"commonName:\s*(['\"])(?P<cn>.+?)\3\s*,\s*"
    r"scientificName:\s*(['\"])(?P<sn>.+?)\5",
)
_IMG = re.compile(r"imageUrl:\s*(['\"])(?P<url>.+?)\1")


def load_birds(birds_js=BIRDS_JS, include_ingested=True):
    """Return [{id, commonName, scientificName, imageUrl}, ...].

    Reads the hand-curated birds.js plus, if present, the generated
    js/birds_ingested.js mass pool — so every media pipeline covers both.
    """
    with open(birds_js, encoding="utf-8") as fh:
        text = fh.read()
    headers = list(_HDR.finditer(text))
    birds = []
    for i, h in enumerate(headers):
        end = headers[i + 1].start() if i + 1 < len(headers) else len(text)
        block = text[h.end():end]
        m = _IMG.search(block)
        birds.append({
            "id": h.group("id"),
            "commonName": h.group("cn"),
            "scientificName": h.group("sn"),
            "imageUrl": m.group("url") if m else "",
        })
    if include_ingested:
        seen = {b["id"] for b in birds}
        for b in load_ingested():
            if b["id"] not in seen:
                birds.append(b)
                seen.add(b["id"])
    return birds


def load_ingested(ingested_js=INGESTED_JS):
    """Parse the generated js/birds_ingested.js JSON array. [] if missing."""
    if not os.path.exists(ingested_js):
        return []
    with open(ingested_js, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"BIRDS_INGESTED\s*=\s*(\[.*\])\s*;", text, re.S)
    if not m:
        return []
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError:
        return []


def save_ingested(birds, ingested_js=INGESTED_JS):
    """Write js/birds_ingested.js as a loadable script wrapping a JSON array."""
    body = json.dumps(birds, indent=2, ensure_ascii=False)
    header = (
        "/* birds_ingested.js — GENERATED by scripts/ingest_birds.py.\n"
        "   Mass pool resolved from Wikipedia + iNaturalist. Loaded before birds.js;\n"
        "   merged into the daily pool by getAllBirds(). Do not edit by hand. */\n"
    )
    with open(ingested_js, "w", encoding="utf-8") as fh:
        fh.write(header + "const BIRDS_INGESTED = " + body + ";\n")


def load_media(media_js=MEDIA_JS):
    """Parse js/media.js → dict. Returns {} if the file is missing/empty."""
    if not os.path.exists(media_js):
        return {}
    with open(media_js, encoding="utf-8") as fh:
        text = fh.read()
    m = re.search(r"BirdMedia\s*=\s*(\{.*\})\s*;", text, re.S)
    if not m:
        return {}
    try:
        return json.loads(m.group(1))
    except json.JSONDecodeError:
        return {}


def save_media(media, media_js=MEDIA_JS):
    """Write js/media.js with a stable, diff-friendly JSON body (sorted keys)."""
    body = json.dumps(media, indent=2, ensure_ascii=False, sort_keys=True)
    header = (
        "/* media.js — GENERATED by scripts/fetch_audio.py and scripts/make_silhouette.py.\n"
        "   Maps bird id -> local media so the game never reveals the answer via a\n"
        "   query-string. Do not edit by hand; re-run the pipelines instead. */\n"
    )
    with open(media_js, "w", encoding="utf-8") as fh:
        fh.write(header + "const BirdMedia = " + body + ";\n")


def update_media_entry(bird_id, **fields):
    """Merge fields into one bird's media entry and persist. Returns the entry."""
    media = load_media()
    entry = media.get(bird_id, {})
    entry.update({k: v for k, v in fields.items() if v is not None})
    media[bird_id] = entry
    save_media(media)
    return entry


def select_birds(birds, ids=None, do_all=False, limit=None):
    """Filter the bird list by --ids / --all / --limit for batch runs."""
    if ids:
        wanted = {x.strip() for x in ids}
        out = [b for b in birds if b["id"] in wanted]
    elif do_all:
        out = list(birds)
    else:
        out = []
    if limit:
        out = out[:limit]
    return out
